### ISSUE TITLE
mail notify apps not working in 5.0.9

### ISSUE THREAD

**Issue by patelbhavin8008** [EELV-fr/mailnotify#11]
i have installed owncloud 5.0.9 on debian wheezy. owncloud is working fine. sharing is also working perfectly fine. I have installed mail notify apps after downloading from GIThub. Apps is enabled and no error found. But when user is sharing the file, other user is not getting any mail. Even green mail icon is also not seen in tab of file.

**Comment by ghost** [comment]
have you add the lib/cronjob.php file to your CronJob Manager. ??

**Comment by ghost** [comment]
same for me

**Comment by ghost** [comment]
shits append in this strange method: db_get_group_by_path($path)

**Comment by ghost** [comment]
hi patelbhavin8008 you can try this one. its only a beta but still work bether then v2.

https://github.com/EELV-fr/mailnotify/releases
