### ISSUE TITLE
Email notification does not get triggered for 1 upload

### ISSUE THREAD

**Issue by o---** [EELV-fr/mailnotify#12]
There seems to be an issue with the email trigger. I only receive an email when I upload at least 2 files. Besides of that, the email gets triggered immediately, so wondering what is the cronjob.php for.

**Comment by ghost** [comment]
on the http://apps.owncloud.com/ version on on the github ?? 
the github is currently between 2 versions, you ca expect broken things.
be shure to have a delay (in sec) for the $minimum_queue_delay var in lib/mailling.php

**Comment by o---** [comment]
I think I have the apps.owncloud.com 2.0.1. I expect broken things, I just wanted to report them. There is no such parameter as $minimum_queue_delay in the /lib/mailing.php in the version I have.

**Comment by ghost** [comment]
hey o--- i have push a v3_RC if you want to try this one. :D  
https://github.com/EELV-fr/mailnotify/releases

**Comment by o---** [comment]
Thank you mate. Much appreciated.  I will give it a go and let you know.
Dňa 15.10.2013 14:51 používateľ "border0464111" notifications@github.com
napísal:

**Comment by o---** [comment]
Hi again,

I took the updated mailing.php file and replaced the existing one. The Mail
Icon on the shared folder does not get activated when I go over with the
cursor.

In Logs I see:
Call to undefined method OC_MailNotify_Mailing::db_is_disabled_for_group()
at /var/www/owncloud/apps/mailnotify/ajax/action.php#15

Then I downloaded the Git version and I got:
Invalid argument supplied for foreach() at
/var/www/owncloud/lib/installer.php#415 (Note, that the directory name I am
using is mailnotify)

Means I was not really able to test it. Besides of that, even this version
still does not support LDAP and my setup has LDAP based users.

Would you be able to incorporate this?

http://pastebin.com/Q9ZgLyQN

Thanks and regards,

----o

**Comment by o---** [comment]
Hi,

I managed to install the git version,  but the problem is still
persistent.  When I upload file1, there is no email.
When I upload file2, I get an email for file1 and file2. When I upload
file3, there is no email till I upload file 4 and than I get the email
again for file3 and file4.

Thanks.

O-----
Dňa 15.10.2013 22:31 používateľ "Android Imo.im" android.imo.im@gmail.com
napísal:

> Hi again,
> 
> I took the updated mailing.php file and replaced the existing one. The
> Mail Icon on the shared folder does not get activated when I go over with
> the cursor.
> 
> In Logs I see:
> Call to undefined method OC_MailNotify_Mailing::db_is_disabled_for_group()
> at /var/www/owncloud/apps/mailnotify/ajax/action.php#15
> 
> Then I downloaded the Git version and I got:
> Invalid argument supplied for foreach() at
> /var/www/owncloud/lib/installer.php#415 (Note, that the directory name I am
> using is mailnotify)
> 
> Means I was not really able to test it. Besides of that, even this version
> still does not support LDAP and my setup has LDAP based users.
> 
> Would you be able to incorporate this?
> 
> http://pastebin.com/Q9ZgLyQN
> 
> Thanks and regards,
> 
> ----o
>

**Comment by o---** [comment]
Sorry mate, taking  back what I send an hour ago. It does not work for me.
I thought I replaced it by the Git version, but I did not.

Now I did and I can not Click the Mail icon to enable emails. It just stays
for me Green line not activated.

Sorry about the confusion caused.

Regars,
o---

**Comment by o---** [comment]
Hello mate,

I managed to fix it partially. The problem I had was in the Database. I
deleted the two tables and recreated them. First two fields are always
primary key.

Than the Icon Enabling and Disabling did not work for me. What I did to fix
it was that I exchanged enabled by disabled and vice versa
in db_user_setting_get_status

Now I have

public static function db_user_setting_get_status($uid, $path){
$path = urldecode($path);
 if(self::get_first_sharing_in($path) !== -1){
$query=OC_DB::prepare('SELECT \* FROM `*PREFIX*mn_usersettings` WHERE `uid`
= ? AND `path` = ?');
$result=$query->execute(array($uid, $path));

if($result->numRows() == 0){
return 'disable';
}else{
return 'enable';
}
}else{
return 'notShared';
}
return 0;
 }

and the icon is working just fine.

But I am not getting any emails what so ever.

Thanks.

o----

**Comment by ghost** [comment]
for the first 2 post, you are right
A lot of file have been changed so you shoud download the whole app.
Database have changed to. Old ones are not compatible and bust be removed by hand.
I have just written Doc on this here: https://github.com/EELV-fr/mailnotify/wiki

But they shoud create them self on activation, but they d'ont.
ill fix that then incorporate your patch. 

Thx for the code&testing

**Comment by ghost** [comment]
*\* database are handled automaticly if version number change. ill fix version number.

icone are working for me without your patch :S . 

icone is green by default telling that notification will be send and turn gray if you click on them telling that notification will not be send . 

or stick with a gray bar if its not shared
if its just write notify without icone its mean ERROR.

Did you see the same thing ?

**Comment by o---** [comment]
Does it mean when there are entries in *mn_settings there are no email notifications for the entries in the table? Otherwise no entries in *mn_settings and notification will be sent for all shared folders?

I had the issue, that I could not even turn the icon to gray. Now it seems to be working fine. :S

**Comment by ghost** [comment]
by default, table is empty and notifications are send. if you want to stop them, you add an entry. That why value columns is always set to disable. That how it was designed in before...

**Comment by o---** [comment]
I still have the trouble to install the app. The only way I got it installed was creating the DB manually. Therefore I do not know, if I am not reporting errors which are there just because it did not install properly.

Now The icon to turn it on and off is not working for me again. The reason is an extra '/' in the directory name. 

In *mn_settings the directory is stored as "/directory" and when checking status, its looking for "//directory". This is coming back with not found and the icon stays green all the times. 

Note, that its been placed there with the leading '/' when I clicked the Icon.

**Comment by o---** [comment]
I managed to receive an email for a file I uploaded. But what I had to do (besides the LDAP Patch) was, I had to change the condition:
<b>from:</b> <i>if (isset($mailTo[0]))</i> <b>to:</b> <i>if (isset($mailTo))</i> because the ARRAY <i>$mailTo</i> where the data is stored looks like this:

<pre>
Array
(
    [username] => Array
        (
            [0] => /filename.jpg
        )
)
</pre>

**Comment by o---** [comment]
I little bug seems to be in sendEmail function. The Name is stored in <b>$toUid</b>, but its using <b>$uid</b>.

**Comment by o---** [comment]
Its not removing uploaded files after a notification has been sent. 

Function <i>db_remove_all_nmuploads_for</i> is receiving in <b>$path</b> the actual <i>/filename.jpg</i> but in the table is stored the fileID like <b>2145</b>.

**Comment by ghost** [comment]
i have push the fix on the fork:
https://github.com/EELV-fr/mailnotify/tree/v3.0.0-rc.1-DEV

I will be happy to integrate your LDAP patch when everything will work.

**Comment by o---** [comment]
The original issue is fixed now. Great Job. Thanks. However I have the issue, that an email does not get triggered when I upload the file in a shared directory. I get emails triggered <b>only</b> when I share the file itself.

**Comment by ghost** [comment]
You can try https://github.com/EELV-fr/mailnotify/releases
