### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by vkonoplev** [EELV-fr/mailnotify#15]
Hello!
I install Mailnotify 3.0.0-RC2
When I add new file to my shared folder, cron tries to send email message.
And I see in log:
{"app":"mail","message":"Invalid address: Mail_Notification@","level":3,"time":"2013-11-15T16:16:01+06:00"}
{"app":"PHP","message":"Invalid address: Mail_Notification@ at \/usr\/share\/php\/PHPMailer \/class.phpmailer.php#664","level":4,"time":"2013-11-15T16:16:01+06:0"}
My E-mail field contain valid e-mail address.
OwnCloud version 5.0.13
PHPMailer I update from GoogleCode to 5.2.4, but the problem remains.(Older version, 5.2.1, gave out the same error on the line 498)
Reports of recovery of the password are sent normally.
What am I doing wrong?

**Comment by ghost** [comment]
oh if password recovery work, it's proabaly an app bug. what is the domain of your email address?? i will take a look at this during the weekend.

**Comment by vkonoplev** [comment]
My email address is my name with domain part @infinet.ru

**Comment by ghost** [comment]
i can't reporduce it :( 
From what i reed of the log, it's like if your $_SERVER[SERVER_NAME] variable wasen't set or invalid.

**Comment by vkonoplev** [comment]
Where can I see the parameter ( $SERVER[SERVERNAME])?
May be I change it to HOSTNAME?

I edit line 140 in mailing.php and change this parameter to real server name string. And the message has come!

**Comment by ghost** [comment]
just create a file foo.php 
and add

```
<?php  
phpinfo();
```

d'ont forget to remove the file after 

I will change it to use the same method the pasword recovery use. that shoud fix it.

**Comment by vkonoplev** [comment]
Hello!
phpinfo result:
....
Apache Environment
SERVER_NAME     ocs.aqua
....
PHP Variables
_SERVER["HTTP_HOST"]    ocs.aqua
_SERVER["SERVER_NAME"]  ocs.aqua
....
This is real my server name.

**Comment by ghost** [comment]
it found that when the cronjob is launch by CLI theres not much usefull variable set, and theres nothing in the owncloud Database for server name. so i have added a variable at the begining of mailnotify.php that can be set manualy.

**Comment by ghost** [comment]
You can try 3.0.0 https://github.com/EELV-fr/mailnotify/releases

**Comment by vkonoplev** [comment]
Hello!
I update mailnotify to last version.
And plugin doesn't to determine correct server name.
I manually changed variables:
private static $cloud_name = 'cloud.aqua';
and
$serverName =  'cloud.aqua';
                                //self::$cloud_name;
And i encountered with  Issue #16.
