### ISSUE TITLE
Disabling notification for partent folder not working ?

### ISSUE THREAD

**Issue by tyleroc** [EELV-fr/mailnotify#18]
Hello and thank you very much for the ongoing development of this great app.
I tried out the latest release (3.0.0) this morning and was very happy to see that all bugs I experienced with the release before have gone.
Unfortunately it seems that it's no longer possible do disable notifications for parent folders. I wish to disable the notification for a folder and if new files will be uploaded to this folder no notification will be send out. With the release 3 RC2 this worked out for me.
Kind regards and thank you in advance,

Tyler

**Comment by ghost** [comment]
Fixed here, 
https://github.com/border0464111/mailnotify/commit/de07b31e9823f004d8f2c35dd39db1ed0881bec1
will be include on next release.
