### ISSUE TITLE
Authentification failure

### ISSUE THREAD

**Issue by Venopsis** [EELV-fr/mailnotify#20]
Hello,

I installed you app today and when I try to access to a folder owncloud says me : "authentification failure". If I disable you app owncloud work normally again.

I'm using Owncloud 6.0.3.

Some screenshots:
• Auth fail : https://dl.dropboxusercontent.com/u/55550180/Mailnotify/Atuh_fail.PNG
• Log: https://dl.dropboxusercontent.com/u/55550180/Mailnotify/Log.PNG

Could you do something please? It's really urgent :/

Thanks.

Cordially, Venopsis.

EDIT: I forgot to say I use the Mailnotify 3.0.0 RC2. I try with the previous version but nothing works. Always the same error.

**Comment by ghost** [comment]
it won't work on OC6. You may try my own repo have made some change to make it work with 6 but havent tested it https://github.com/border0464111/mailnotify

For now, i can't put more time on this sorry 

Date: Wed, 18 Jun 2014 04:11:53 -0700

**Comment by Venopsis** [comment]
Hello,

Thank you very much to answer me. No problem I can understand we have all a live first ;)

I'll try that https://github.com/border0464111/mailnotify. I hope it will work. I give you my feedback when i 'll have tried it ;)

Cordially, Venopsis.

**Comment by Venopsis** [comment]
Unfortunately I've got always the same authentication error :/

I don't know PHP so it's not possible for me to try to change the app to work with OC 6.x :(

I close the ticket.
