### ISSUE TITLE
Mailnotify doesn`t work with OC 5.0.7??

### ISSUE THREAD

**Issue by hwk06** [EELV-fr/mailnotify#5]
Hey there,
I have installed this app on a new OC-Installation with 5.0.7.
The App was succesfull enabled, and the shared Folder shows the image in the attachement picture below. But it seems, it doesn`t work. After i upload a new file, it doesn`t sends a email to me. 
All other emails e.g "share a link per Email" works great.

![unbenannt](https://f.cloud.github.com/assets/4737591/674199/430732ba-d8cf-11e2-820b-8489903228cf.jpg)

Is it possible to get some help?

System:
Windows 2008 Server with IIS 7.0
PHP Version 5.4.16
a manual batchfile to run the cronjob.php exists

Thanks!!
hwk06

**Comment by telcy** [comment]
Should be fixed. Otherwise open a new issue.
