### ISSUE TITLE
Not working with ownCloud 5.0.9 (and prior?) - Solution

### ISSUE THREAD

**Issue by beebodo** [EELV-fr/mailnotify#6]
After activating MailNotify on 5.0.9 I could not change the status of a shared folder. The behaviour was like described below.
- Shared folders are always taken as enabled, green envelope is always shown on shared folders
- MailNotify is not able to enable oder disable shared folders and add entries to the settings database

To my mind this is an error in mailing.php. 
In function "db_is_disabled_for_group" the check for the returned number of entries in the result set is not correct.

Actual:  ... if($count >= 1){ ...
Should be: ... if($count == 0){ ...

After changing the code, the behaviour is as expected.

beebodo

**Comment by telcy** [comment]
Should be fixed. Otherwise open a new issue.
