### ISSUE TITLE
Problems in MailNotify 2.0.1

### ISSUE THREAD

**Issue by beebodo** [EELV-fr/mailnotify#7]
Even after updating to 2.0.1. the notification email is not reliably sent the way I expect it to be sent.
To my mind there is some more work to be done in mainling.php to make it run:

```
public static function db_user_disabled_notify($uid, $gid){
[...]
```

//      $query=OC_DB::prepare('SELECT \* FROM `*PREFIX*mn_usersettings` WHERE `uid` = ? AND `group` LIKE ? AND `value`=2');
// The result seems always to be empty as I cannot find any place where '2' is stored in the table.
// Accordingly to this no email will be sent if function below is corrected.
        $query=OC_DB::prepare('SELECT \* FROM `*PREFIX*mn_usersettings` WHERE `uid` = ? AND `group` LIKE ? AND `value`=1');  
    [...]
    }

```
public static function db_notify_group_members(){
[...]   
            foreach($users as $user){
                    //$uid = OCP\User::getUser();   
```

//                      if($sent_to_owner == false and !self::db_user_disabled_notify($user['uid_owner'], $folder)){  
// if function above (db_user_disabled_notify) is corrected no negation is required
                        if($sent_to_owner == false and self::db_user_disabled_notify($user['uid_owner'], $folder)){  
                                $mail = self::db_get_mail_by_user($user['uid_owner']);
                                self::email($mail,$count,$str_filenames,$folder,$user['uid_owner']);
                                $sent_to_owner = true;
                        }
                        $mail = self::db_get_mail_by_user($user['share_with']); 
//                      if($mail != '' and !self::db_user_disabled_notify($user['share_with'], $folder)){  
// if function above (db_user_disabled_notify) is corrected no negation is required
                        if($mail != '' and self::db_user_disabled_notify($user['share_with'], $folder)){  
                                self::email($mail,$count,$str_filenames,$folder,$user['uid_owner']);  
                        }  
                }
    [...]  
    }

After doing these changes a user can reliably bookmark a shared folder and get informed about changes in this folder.

Unfortunately it doesn't work well on files in subfolders of shared folders.
For example:
If you have a folder structure like /Folder/Folder1/Folder2/Folder3 and Folder2 is shared with a user, the notification for Files in Folder3 doesn't work.
I think at this point a different strategy has to be implemented.

The good thing of the update:
Selecting and deselecting folders for notfification works as expected now. ;-)

beebodo

**Comment by telcy** [comment]
Thanks for report. We're fixing it currently.

**Comment by telcy** [comment]
- fixed bug if shared folder contains not shared sub folders
- fixed database query 2 -> 1

Feel free to open a new issue if something doesn't work as expected.
