### ISSUE TITLE
Last update doesn't work

### ISSUE THREAD

**Issue by beebodo** [EELV-fr/mailnotify#8]
After installing the actual update (2013/07/25) of MailNotify 2.0.1 no notification is generated - at least in the standard scenario (Upload in shared top folder). 

To solve this, I changed two things in mailing.php:
- Removed two "!" (negations) in  "!self::db_user_disabled_notify"
  (at function db_notify_group_members, lines 352 and 355 of mailing.php)
  (I recommended this also in my last issue)
- Changed line 443 (function db_get_group_by_path) of mailing.php to 
  return $splits[count($splits)-2];

With the changes documents above it now works fine no matter if documents are placed in a top folder or a subfolder of a share and no matter if the share is a full OC path or a subpath. ;-) 

But it seems that it doesn't work if I call the script via the cronjob.php:
"sudo /usr/bin/php5 /var/www/owncloud/apps/mailnotify/lib/cronjob.php" ;-(

beebodo

**Comment by ghost** [comment]
seem to have been fixed here 
https://github.com/EELV-fr/mailnotify/commit/c9d16705310167e2cdf6b7091fe1051151e99c86
